### ISSUE TITLE
[seahawk-rov-spare.local] ROV upstart fails

### ISSUE THREAD

**Issue by MKVollmer25** [CabrilloRoboticsClub/cabrillo_rov_2023#122]
**Describe the bug**

**To Reproduce**
1. Start up seahawk-rov-spare.local
2. Run systemctl status seahawk_rov_upstart.service
3. See error

**Expected behavior**
The ROS program should be running on startup

**Screenshots / Error messages**
```python
Apr 28 22:36:44 SeaHawk-ROV-SPARE systemd[1]: Started "bringup seahawk_rov_upstart".
Apr 28 22:36:52 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1104]: ls: cannot access '/etc/ros/humble/seahawk_rov_upstart.d/*.xacro': No such file or directory
Apr 28 22:36:54 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [INFO] [launch]: All log files can be found below /tmp/2023-04-28-22-36-54-265004-SeaHawk-ROV-SPARE-1110
Apr 28 22:36:54 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [INFO] [launch]: Default logging verbosity is set to INFO
Apr 28 22:36:55 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [INFO] [h264_cam_node-1]: process started with pid [1112]
Apr 28 22:36:55 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [INFO] [seahawk_rov-2]: process started with pid [1114]
Apr 28 22:36:55 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [INFO] [static_transform_publisher-3]: process started with pid [1116]
Apr 28 22:36:56 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [static_transform_publisher-3] [INFO] [1682721416.011022804] [imu_transform]: Spinning until stopped - publishing transform
Apr 28 22:36:56 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [static_transform_publisher-3] translation: ('0.170000', '0.050000', '0.070000')
Apr 28 22:36:56 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [static_transform_publisher-3] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
Apr 28 22:36:56 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [static_transform_publisher-3] from 'base_link' to 'logic_tube_bno085'
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1] [INFO] [1682721417.374792137] [front_camera]: Parameter input_fn: /dev/video0
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1] [INFO] [1682721417.377670692] [front_camera]: Parameter fps: 30
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1] [INFO] [1682721417.378550914] [front_camera]: Parameter size: 1280x960
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1] [INFO] [1682721417.378666451] [front_camera]: Parameter frame_id: front_camera
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1] [INFO] [1682721417.378717544] [front_camera]: Parameter camera_info_path: info.ini
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1] [video4linux2,v4l2 @ 0xaaaae9d29b30] Cannot open video device /dev/video0: Permission denied
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1] [ERROR] [1682721417.402710618] [front_camera]: Could not open the v4l device: /dev/video0
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1] terminate called after throwing an instance of 'std::runtime_error'
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [h264_cam_node-1]   what():  Could not open the v4l device
Apr 28 22:36:57 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [ERROR] [h264_cam_node-1]: process has died [pid 1112, exit code -6, cmd '/home/ubuntu/cabrillo_rov_2023/install/h264_image_transport/lib/h264_image_transport/h264_cam_node --ros-args -r __node:=front_camera --params-file /tmp/launch_params_ryiwas1n -r image_raw/h264:=front_camera/h264'].
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2] Traceback (most recent call last):
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]   File "/home/ubuntu/cabrillo_rov_2023/install/seahawk_rov/lib/seahawk_rov/seahawk_rov", line 33, in <module>
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]     sys.exit(load_entry_point('seahawk-rov', 'console_scripts', 'seahawk_rov')())
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]   File "/home/ubuntu/cabrillo_rov_2023/build/seahawk_rov/seahawk_rov/__main__.py", line 75, in main
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]     i2c = board.I2C()
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]   File "/home/ubuntu/.local/lib/python3.10/site-packages/board.py", line 320, in I2C
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]     return busio.I2C(SCL, SDA)
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]   File "/home/ubuntu/.local/lib/python3.10/site-packages/busio.py", line 35, in __init__
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]     self.init(scl, sda, frequency)
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]   File "/home/ubuntu/.local/lib/python3.10/site-packages/busio.py", line 123, in init
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]     self._i2c = _I2C(portId, mode=_I2C.MASTER, baudrate=frequency)
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]   File "/home/ubuntu/.local/lib/python3.10/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 27, in __init__
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]     self._i2c_bus = smbus.SMBus(bus_num)
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]   File "/home/ubuntu/.local/lib/python3.10/site-packages/Adafruit_PureIO/smbus.py", line 125, in __init__
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]     self.open(bus)
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]   File "/home/ubuntu/.local/lib/python3.10/site-packages/Adafruit_PureIO/smbus.py", line 151, in open
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2]     self._device = open("/dev/i2c-{0}".format(bus), "r+b", buffering=0)
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [seahawk_rov-2] PermissionError: [Errno 13] Permission denied: '/dev/i2c-1'
Apr 28 22:36:58 SeaHawk-ROV-SPARE seahawk_rov_upstart-start[1110]: [ERROR] [seahawk_rov-2]: process has died [pid 1114, exit code 1, cmd '/home/ubuntu/cabrillo_rov_2023/install/seahawk_rov/lib/seahawk_rov/seahawk_rov --ros-args -r __node:=seahawk_rov'].
```

**Additional context**
Manually launching seahawk_rov works just fine, the launch only fails when done with the robot_upstart service.

**Comment by DerVerrater** [comment]
The script directory for robot_upstart is missing, or inaccessible by the daemon. Creating the directory will silence the warning, but the fact that it's missing could indicate that there's an installation issue. The upstart scripts are meant to live there, and they aren't.

The node seems to start up in spite of this, though. The node failure is because the program doesn't have access to the device nodes `/dev/i2c-1` (for the seahawk_rov node) and `/dev/video0` (for the h264_cam_node). I expect this to be the robot_upstart script using a different user than the one you use when launching manually. The service scripts should be modified to run the ROS2 Nodes as the appropriate user (or permissions granted to the one it's already trying to run as).

I think the use of robot_upstart is more effort than it's worth, and we should just supply our own Systemd unit files -- or accept that our startup procedure includes an SSH session and manual start. It's easy enough, and we're under time pressure.
